### ISSUE TITLE
[BUG] Feedback Rating이 반영되지 않는 문제

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#103]
**Describe the bug**
https://github.com/manito42/backend/blob/9fec13a5b93e43a985dcb15827d9ea177c590a44/src/database/repository/reservation.repository.ts#L218-L271
- PATCH API에 Rating을 건냈음에도 rating이 반영되지 않음.

**To Reproduce**
- PATCH reservations/id/mentee_completion

**Expected behavior**
- id 가 변경되어야 함

**Screenshots**
<img width="673" alt="image" src="https://github.com/manito42/backend/assets/81505228/d8c00cb1-e334-4cb5-afcb-08357399f1ae">

**Additional context**
- 코드 확인해보니 data 에 rating을 반영하지 않는 것 같습니다.

**Comment by koreanddinghwan** [comment]
> **Describe the bug**
> 
> https://github.com/manito42/backend/blob/9fec13a5b93e43a985dcb15827d9ea177c590a44/src/database/repository/reservation.repository.ts#L218-L271
> 
> * PATCH API에 Rating을 건냈음에도 rating이 반영되지 않음.
> 
> **To Reproduce**
> 
> * PATCH reservations/id/mentee_completion
> 
> **Expected behavior**
> 
> * id 가 변경되어야 함
> 
> **Screenshots** <img alt="image" width="673" src="https://user-images.githubusercontent.com/81505228/269197728-d8c00cb1-e334-4cb5-afcb-08357399f1ae.png">
> 
> **Additional context**
> 
> * 코드 확인해보니 data 에 rating을 반영하지 않는 것 같습니다.

저번에 rating implementation 안하기로 했었던걸로 알고있습니다. 포함하실계획인가요?

**Comment by koreanddinghwan** [comment]
<img width="705" alt="스크린샷 2023-09-20 18 48 45" src="https://github.com/manito42/backend/assets/76278794/45fc2ddd-5d94-45ce-8f64-b3cc1e86fe2e">

**Comment by koreanddinghwan** [comment]
> 아 깜빡하고 있었네요... 프론트 작업하면서 일단 구현은 해둔 상태입니다. 빼는건 어렵지 않아서 금방 수정하긴합니다. <img alt="image" width="485" src="https://user-images.githubusercontent.com/81505228/269234047-d16c7896-af59-43e2-a267-4a666e07e47c.png">
> 
> 매번 작업하면서 갈팡질팡하네요 ... 당시에 별점이 서로 기분 문제도 있었던 것 같아서 그렇게 결정했었죠? rating sum 만 빠진줄 알고 착각한듯...
> 
> +++ 일단은 rating db 상에는 존재하고 있어서 하더라도 5.0 으로 두는게 맞는 것 같습니다. 별개로, mentee -> mentor (후기만 남김) mentor -> mentee ( 확인 버튼 누르고 끝)
> 
> 이렇게 가는거 맞았나요?

https://github.com/manito42/backend/wiki/Reservation

**Comment by JuneParkCode** [comment]
요건 알고 있는데, rating  포함 / 미포함에 따라서 프론트의 뷰가 조금 달라집니다.

<img width="488" alt="image" src="https://github.com/manito42/backend/assets/81505228/314aec44-432d-4cd4-8612-ab84d4111000">


여기서 리뷰 등록하고 넘어갈지 (모달 뜨고, rating 받음) 아니면 단순 확인 버튼으로 끝날지...

**Comment by koreanddinghwan** [comment]
rating 포함하는게 좋아보여요

**Comment by koreanddinghwan** [comment]
백엔드도 rating 받아서 처리하는걸로 남겨둘게요
