### ISSUE TITLE
MySQL DB (RDS) 구축

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#19]

**Comment by koreanddinghwan** [comment]
## Parameter Group

- ![database timezone setting](https://repost.aws/knowledge-center/rds-change-time-zone)

**Comment by JuneParkCode** [comment]
TZ 이야기를 안했었네요. API 서버 또한 Asia/Seoul 로 사용하고 있습니다.
 현재는 시간과 관련된 정보를 조회할 일이 없는데, 추후 이런 저런 기능 들어오고, 만약 타 캠퍼스 확장을 생각하면 UTC로 맞추는게 맞나 싶기도 하고 ...

**Comment by koreanddinghwan** [comment]
> TZ 이야기를 안했었네요. API 서버 또한 Asia/Seoul 로 사용하고 있습니다.
> 
>  현재는 시간과 관련된 정보를 조회할 일이 없는데, 추후 이런 저런 기능 들어오고, 만약 타 캠퍼스 확장을 생각하면 UTC로 맞추는게 맞나 싶기도 하고 ...
> 
> 

프론트와도 상의하는게 좋을 것 같습니다


시간 변환에 대한 책임을 어디에 둘 것인가? 프론트에서하면 번들링 이슈가 있을거고(Next라고 순수 리액트보다는 적음) 
백에서하면 클라이언트의 캠퍼스 정보마다 시간정보를 세팅하는 등의 의사결정이 필요하겠네여
