### ISSUE TITLE
VPC관련

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#21]
VPC에 Manito vpc있던데, 따로 VPC생성해서 하나요?   

- no: test_server가 사용중인 기본 VPC사용하면될까요?
- yes: Internet Gateway따로 필요한데, 생성해서 사용해도되나요

**Comment by JuneParkCode** [comment]
새로 생성합시다. 지금 이해가 없는 상태에서 적용되어서 테스트 용으로 작성된 VPC 입니다.
제가 처음 다루는 부분이라 공부가 필요해서, 하실 때 같이할 수 있으면 좋겠슴다.
