### ISSUE TITLE
ELB (Application Load Balancer)구축

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#26]
# ELB 
## DEV / PRODUCTION
- [x] dev
- [x] production
## Auto Scaling
- [x] Desire : 1
- [x] Min : 1
- [x] Max : 2
- [x] Template -> node 18.16 / Code deploy
- [x] private subnet
## Network
- [x] Public Subnet
- [x] Target => Auto scaling group
## CHECK
- [x] **DONE**

**Comment by JuneParkCode** [comment]
@koreanddinghwan 더 할 것 있으면 추가 부탁드립니다...

**Comment by koreanddinghwan** [comment]
template에 사용하실 AMI는 AMI 리스트 중에서 latest 붙어있는거 사용하시면됩니다.

**Comment by JuneParkCode** [comment]
Production / Development 모두 적용 완료
