### ISSUE TITLE
SSH agent forwarding을 통한 private subnet의 ec2 instance 접근방법

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#28]
[ssh forwarding set in config](https://superuser.com/questions/950406/how-to-do-ssh-agent-forwarding-on-mac-terminal)    
[how to access private subnet instances](https://digitalcloud.training/ssh-into-ec2-in-private-subnet/)   

1. 모든 인스턴스들에 동일한 key-pem 접속 설정
2. 맥북의 ~/.ssh 의 config에 `ForwardAgent yes` 설정.
3. public subnet instance에 대해서 ssh 접속 후, private subnet 인스턴스에 동일한 방식으로 접속.

**Comment by JuneParkCode** [comment]
Production / Development 모두 적용완료
