### ISSUE TITLE
2023.07.06 이슈

### ISSUE THREAD

**Issue by 9utty** [manito42/backend#3]
1. 로그인 성공시 uId 같이 반환하게
2. 멘토와 멘티의 상태를 보여 줄 필요가 있어서 User안에 reservation 컬럼이 필요하다고 생각(Mentore, Mentee도 나눠야함)
3. User에 MenteeRate, MentorRate가 필요할 것 같습니다! 물론 나중에 기능추가 해야하지만 나중을 위해서 만들어둘 필요가 있다고 생각합니다! ( 추후에 한번더 이야기하시죠! )
4. User에 이번달 멘토링 횟수, 총 멘토링 횟수 컬럼이 필요합니다.

**Comment by 9utty** [comment]
@JuneParkCode

**Comment by JuneParkCode** [comment]
/user/{id}/reservation 이 필요함
- 쿼리에서 상태 구분하여 필터링 할 수 있도록 함.
- 이 때, 멘토로서의 예약과 멘티로서의 예약을 구분하여 response 해야함

**Comment by JuneParkCode** [comment]
2번은 위 코멘트로 대체되고, 3번의 경우 추가 검토 후 칼럼 추가, 4번의 경우 컬럼 보다는 다른 방식의 접근을 고려해보겠습니다.
