### ISSUE TITLE
Winston log file 영속화를 위한 EFS 연동

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#30]

**Comment by koreanddinghwan** [comment]
# efs 및 asg security group

- EFS는 기본적으로 NFSv4를 사용합니다. NFSv4는 TCP기반입니다.

## EFS

![스크린샷 2023-08-20 03 22 59](https://github.com/manito42/backend/assets/76278794/88d133e5-2c47-40b2-8156-feedbb3e66ed)

![스크린샷 2023-08-20 03 23 12](https://github.com/manito42/backend/assets/76278794/f6103bd7-d71f-4364-9193-91ec300c26d5)

## ASG

outbound로 NFS허용

<br><br>

# AMI 설정

- ubuntu ami기반이므로, 수동으로 `amazon-efs-utils`를 설치해야합니다.

[NFS client 설치](https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html)


```sh
- echo "$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).[efs-id].efs.ap-northeast-2.amazonaws.com:/    /var/www/html/efs-mount-point   nfs4    defaults" >> /etc/fstab
```

- 위에서 efs-id만 efs의 id로 변경합니다.
- 커맨드 실행 후, /etc/fstab에 efs dns로 된 줄이 있어야합니다.

<br><br>

# ASG 시작템플릿 설정

1. 위에서 생성한 AMI로 변경합니다.
2. 고급 세부정보의 사용자 데이터에 아래와 같은 커맨드를 입력합니다.

![스크린샷 2023-08-20 03 27 36](https://github.com/manito42/backend/assets/76278794/e8cae092-c88d-4073-9638-10312141232e)

이 커맨드는 인스턴스 부팅/재부팅 시에 자동으로 수행됩니다.


<br><br>

# bastion host 설정

현재 development 서버의 로그는 /home/ec2-user/api-server에 있습니다.   

<img width="678" alt="스크린샷 2023-08-20 03 32 32" src="https://github.com/manito42/backend/assets/76278794/a9ba3557-2084-4a81-bb7c-229888fd77d1">

<br>

bastion host역시 위의 AMI설정을 그대로 따라가시면됩니다.

**Comment by koreanddinghwan** [comment]
# efs 및 asg security group

- EFS는 기본적으로 NFSv4를 사용합니다. NFSv4는 TCP기반입니다.

## EFS

inbound/outbound로 NFS허용

## ASG

outbound로 NFS허용

<br><br>

# AMI 설정

- ubuntu ami기반이므로, 수동으로 `amazon-efs-utils`를 설치해야합니다.

[NFS client 설치](https://docs.aws.amazon.com/efs/latest/ug/installing-amazon-efs-utils.html)


```sh
- echo "$(curl -s http://169.254.169.254/latest/meta-data/placement/availability-zone).[efs-id].efs.ap-northeast-2.amazonaws.com:/    /var/www/html/efs-mount-point   nfs4    defaults" >> /etc/fstab
```

- 위에서 efs-id만 efs의 id로 변경합니다.
- 커맨드 실행 후, /etc/fstab에 efs dns로 된 줄이 있어야합니다.

<br><br>

# ASG 시작템플릿 설정

1. 위에서 생성한 AMI로 변경합니다.
2. 고급 세부정보의 사용자 데이터에 아래와 같은 커맨드를 입력합니다.

![스크린샷 2023-08-20 03 27 36](https://github.com/manito42/backend/assets/76278794/e8cae092-c88d-4073-9638-10312141232e)

이 커맨드는 인스턴스 부팅/재부팅 시에 자동으로 수행됩니다.


<br><br>

# bastion host 설정

현재 development 서버의 로그는 /home/ec2-user/api-server에 있습니다.   


<br>

bastion host역시 위의 AMI설정을 그대로 따라가시면됩니다.

**Comment by JuneParkCode** [comment]
Production / Develop 적용 완료
