### ISSUE TITLE
reservation 관련된 문의

### ISSUE THREAD

**Issue by 9utty** [manito42/backend#4]
```
{
    "id": 0,
    "mentorId": 0,
    "menteeId": 0,
    "categoryId": 0,
    "requestMessage": "string",
    "status": "REQUESTED",
    "createdAt": "2023-07-06T08:03:03.773Z",
    "updatedAt": "2023-07-06T08:03:03.773Z",
    "hashtags": [
      {
        "id": 0,
        "name": "string"
      }
    ]
  }
  ```
  
현재 받는 DTO 인거 같은데 일단 배열로 받는다는건 알겠지만, 

Enroll Page 구성중에 Mentor state, Mentee state를 작업하려고 하는 중에 
  
URL/reservation/을 하면 Mentor, Mentee 개체를 주거나, 
URL/reservation/mentor, URL/reservation/mentee 같은게 필요할 것 같습니다! 

만약에 받더라도 status가 "ACCEPT", "REQUEST"만 받을 수 있게 하면 될 것 같습니다!

그리고 CANCEL에 대한 API,  REQUEST API, ACCEPT API 가 필요할 것 같습니다!

**Comment by JuneParkCode** [comment]
/reservation 에서 reservation의 상태에 따라 필터링 할 수 있도록 쿼리를 구성하도록 하겠습니다.
