### ISSUE TITLE
Hashtag관련 내용

### ISSUE THREAD

**Issue by 9utty** [manito42/backend#5]
현재는 만약 존재하는 hashtag면 409 already exists를 주고 있습니다!
여기서 필요하다고 생각되는 부분은 409보다는 200으로 있는 개체를 주시면 편할 것 같습니다!
```
{
  "id": 0,
  "name": "string"
}
```

**Comment by JuneParkCode** [comment]
6656943603b5b6e6f966e39952e02e2791a60a70
해결되었습니다.
