### ISSUE TITLE
[Todo] CI/CD 관련 Action이 특정 상황에서 Disable 될 수 있도록 변경

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#56]
## Description
- 현재 Github action 의 경우 on push 상황에서 '항상' Deployment 가 진행됨
- 그러나, readme 변경과 같이 코드에 영향을 미치지 않을 경우 해당 행위는 비효율적임.
- 따라서, 특정 상황에서는 Action이 실행되지 않도록 보장할 수 있어야함.

**Comment by JuneParkCode** [comment]
https://github.com/orgs/community/discussions/50868
https://libertegrace.tistory.com/entry/Github-Actions-%ED%8A%B9%EC%A0%95-%ED%8C%8C%EC%9D%BC%EC%9D%B4%EB%82%98-%ED%8F%B4%EB%8D%94%EC%97%90-%EB%8C%80%ED%95%B4%EC%84%9C%EB%A7%8C-Github-Actions%EA%B0%80-trigger%EB%90%98%EB%8A%94-%EB%B0%A9%EB%B2%95

**Comment by koreanddinghwan** [comment]
https://github.com/orgs/community/discussions/25369

전체 폴더에 대한 include 이후/ exclude할 경로만 지정
