### ISSUE TITLE
[Bug] dev 환경 프론트 배포시 login이 안되는 문제

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#57]
## Description
- localhost:3000/signin? 으로 넘어갑니다.

## Solution
- dev.42manito.com 으로 redirection 할 수 있도록 변경

## Comment
- 이전에 언급했던 내용인데, localhost 환경에서 작업하는걸 고려했던걸로 기억합니다.
- redirection 되는 부분이 저거 밖에 없어서, front에서 아마 직접 token 주입하여 해결할 수 있을 것으로 보입니다.
- 따라서, 기본적으로 redirection 은 dev.42manito.com 으로 할 수 있도록 해주세요.

**Comment by koreanddinghwan** [comment]
## 변경사항

1. 레포지토리 환경변수 변경완료
2. 실행중인 인스턴스에서 변경완료

- 빌드시에 환경변수가 대치되기 때문에 재배포해야 적용됩니다. 현재 인스턴스 내부에선 빌드가 안되기때문에...

**Comment by koreanddinghwan** [comment]
> ## 변경사항
> 1. 레포지토리 환경변수 변경완료
> 2. 실행중인 인스턴스에서 변경완료
> 
> * 빌드시에 환경변수가 대치되기 때문에 재배포해야 적용됩니다. 현재 인스턴스 내부에선 빌드가 안되기때문에...

잠시만요 다시 확인해볼게요

**Comment by koreanddinghwan** [comment]
설정완료했습니다

**Comment by JuneParkCode** [comment]
넵넵 내부 변수 바뀐거 확인했습니다.
