### ISSUE TITLE
[Bug] pm2 log쌓이는 문제

### ISSUE THREAD

**Issue by koreanddinghwan** [manito42/backend#60]
## Description

- 따로 사용중인 winston logger 이외에 pm2 log가 /root/.pm2 에 쌓이고있습니다.

## 해결방법

1. 윈스톤 로거 사용중이므로 pm2의 log 기능 비활성화
2. EFS에 따로 연동하기

**Comment by JuneParkCode** [comment]
해당 로그가 저희한테 도움이 된다면 EFS로 빼는게 맞는 것 같고 아니라면 비활성화가 맞을 것 같습니다.

**Comment by koreanddinghwan** [comment]
pm2 log는 비활성화하는 방안으로 하겠습니다 윈스톤로거랑 겹칠것같습니다
