### ISSUE TITLE
[Bug] PATCH /MentorProfiles 에서 description 이 아무것도 없는 경우

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#65]
## Description
- 소개글을 모두 지운 경우, 지우는 행위를 해야하는데 업데이트를 안합니다.
- DTO 와 내부 로직 변경이 필요합니다.

**Comment by koreanddinghwan** [comment]
# 1안 

- MinLength를 해제, null과 ''이 description에 들어올 수 있게됨

```ts
    /**
     *     {
     *       id: 31,
     *       userId: 31,
     *       shortDescription: null,
     *       description: null,
     *       isHide: false,
     *       mentoringCount: 0,
     *       createdAt: 2023-09-02T13:38:16.000Z,
     *       updatedAt: 2023-09-02T13:38:16.000Z
     *     }
     * */

    /**
     *     {
     *       id: 31,
     *       userId: 31,
     *       shortDescription: '',
     *       description: '',
     *       isHide: false,
     *       mentoringCount: 0,
     *       createdAt: 2023-09-02T13:38:16.000Z,
     *       updatedAt: 2023-09-02T13:38:16.000Z
     *     }
     * */

```



# 2안 (현재 유지)

작성자가 description을 모두 삭제한 경우/ body의 property-> description을 null로 서버에 보내면

```ts
    /**
     *     {
     *       id: 31,
     *       userId: 31,
     *       shortDescription: null,
     *       description: null,
     *       isHide: false,
     *       mentoringCount: 0,
     *       createdAt: 2023-09-02T13:38:16.000Z,
     *       updatedAt: 2023-09-02T13:38:16.000Z
     *     }
     * */
```

**Comment by koreanddinghwan** [comment]
> 

@JuneParkCode

**Comment by JuneParkCode** [comment]
후자로 처리해야할 것 같습니다. 그러면 프론트쪽에서 따로 처리를 하면 되는걸까요?

**Comment by koreanddinghwan** [comment]
네 그렇습니다.

1. 최초 회원가입시 description은 모두 null
2. 프론트 측에서 렌더링 시 프로필의 description이 null일경우, default 문구를 표현

### 클라이언트가 description 작성하다가 맘에 안들어서 모두 지울때

length가 0이면 property에 포함해서 보내지 않음.

**Comment by koreanddinghwan** [comment]
> 네 그렇습니다.
> 
> 1. 최초 회원가입시 description은 모두 null
> 2. 프론트 측에서 렌더링 시 프로필의 description이 null일경우, default 문구를 표현
> 
> ### 클라이언트가 description 작성하다가 맘에 안들어서 모두 지울때
> length가 0이면 property에 포함해서 보내지 않음.

서버쪽 관련된 테스트코드 e2e로 집어넣고 PR날리겠습니다

**Comment by JuneParkCode** [comment]
넵 확인해보겠습니다. 일단 프론트쪽 해결될 때까지 해당 이슈는 오픈해두겠습니다.
