### ISSUE TITLE
[Fix] Reservation 프로세스에 CHECKED 추가

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#66]
## Description
- 프론트엔드에서 Reservation 관련한 부분에서 수정사항이 있어 Mentee 의 확인 절차가 필요합니다.

## Todo
- [ ] Accept 이후에 멘티가 Accept 된 사실을 확인하는 절차가 필요합니다.
- [ ] GET /reservations/:id/checked 추가

## 프론트엔드
- 관련 이슈 해당 이슈에 등록해두겠습니다.

**Comment by koreanddinghwan** [comment]
frontend issue 태그 부탁드립니다

**Comment by koreanddinghwan** [comment]
https://github.com/orgs/manito42/discussions/94

**Comment by koreanddinghwan** [comment]
> ## Description
> * 프론트엔드에서 Reservation 관련한 부분에서 수정사항이 있어 Mentee 의 확인 절차가 필요합니다.
> 
> ## Todo
> * [ ]  Accept 이후에 멘티가 Accept 된 사실을 확인하는 절차가 필요합니다.
> * [ ]  GET /reservations/:id/checked 추가
> 
> ## 프론트엔드
> * 관련 이슈 해당 이슈에 등록해두겠습니다.

- 이 [discussion](https://github.com/i12cu84?tab=followers)의 연장선 입니다.

### 현재 프로세스

1. 멘토링 요청 생성 - REQUEST
2. 멘토의 멘토링 수락 - ACCEPT
3. 멘티의 멘토링 피드백 - MENTEE_FEEDBACK
4. 멘토의 멘토링 피드백 - DONE

### 변경된 프로세스

1. 멘토링 요청 생성 - REQUEST
2. 멘토의 멘토링 수락 - ACCEPT
3. 멘티의 멘토링 확인 - MENTEE_CHECKED
4. 멘티의 멘토링 피드백 - MENTEE_FEEDBACK
5. 멘토의 멘토링 피드백 - DONE

확인 부탁드립니다

**Comment by JuneParkCode** [comment]
넵 맞습니다.

**Comment by koreanddinghwan** [comment]
![image](https://github.com/manito42/backend/assets/76278794/a8cfc927-551d-4609-bc92-bc024da8924d)

**Comment by JuneParkCode** [comment]
알림은 우선 내버려둘까요? 서로 확인하는걸 보는 절차인데 알림이 필요할까 싶네요.

**Comment by koreanddinghwan** [comment]
![image](https://github.com/manito42/backend/assets/76278794/aa7bdeb8-ece4-4dc8-9c13-965536b798b0)

**Comment by koreanddinghwan** [comment]
수정했습니다 mentee가 확인한 이후에 멘토측에서 취소가능하게끔 했습니다

**Comment by koreanddinghwan** [comment]
> 알림은 우선 내버려둘까요? 서로 확인하는걸 보는 절차인데 알림이 필요할까 싶네요.

네 저도 굳이라는 생각이 들긴합니다

**Comment by koreanddinghwan** [comment]
![image](https://github.com/manito42/backend/assets/76278794/73acb902-ca95-468d-a552-daa2afc2e414)
이걸로 최종본해서 wiki에 올려두겠습니다~

**Comment by JuneParkCode** [comment]
넵 좋습니다!
