### ISSUE TITLE
User Reservation APi 변경

### ISSUE THREAD

**Issue by JuneParkCode** [manito42/backend#83]
## /user/{:id}/reservations/*
- 유저의 예약 상태를 가져옵니다.
- 하위 api는 모두 pagination을 지원합니다.
- 다음과 같은 목적으로 사용합니다.
  - 나의 모든 멘토링 조회
  - 멘토로서의 멘토링 조회
  - 멘티로서의 멘토링 조회
  - 위 두 분류에서 다시 아래 분류를 지원해야합니다.
    - 대기 중인 멘토링 조회 (REQUEST, ACCEPT)
    - 진행 중인 멘토링 조회 (MENTEE_CHECK, MENTEE_FEEDBACK)
    - 완료된 멘토링 조회 (DONE, CANCEL)
    - 각자 상태별  조회
    - 전체 상태 조회

### 논의 필요
- 프론트 입장에서는 쿼리를 통해서 날리는게 편하긴 합니다.
- 예를 들자면, 다음과 같습니다. 두 가지 방법 정도 있을 것 같네요.
  - **1. 상태별로 따로 파기**
    - as_,mentee / as_mentor 사용해도 되고...
     - `/user/id/reservations` 경로를 앞으로 `.` 라고 하겠습니다.
    - `.`
      - pagination 관련 query만 받음
      - 전체 예약에 대해서 제공
    - `./requests`
      - role: mentee | mentor
      - pagination 제공
    - `./in_progress` or `./active`
      - role: mentee | mentor
      - pagination 제공
   - `./done`
      - role: mentee | mentor
      - pagination 제공
      - cancel, done 분리 가능
   - **2. `.` 에서 모두 제공**
   - 범용적이기도 하고, 프론트에서 깔끔하긴 합니다.
     - query parameter (default)
       - take (20)
       - page (0)
       - role : mentee | mentor | all (all)
       - status query (all true)
         - request, accept, mentee_check, mentee_feedback, done, cancel
         - 이걸 좀 깔끔하게 하는 방법이 있을 것 같기도한데... 있는지 잘 모르겠네요.

**Comment by JuneParkCode** [comment]
이거 작업은 제가 하겠습니다..
저번에 쿼리에서 분리하고 했던 내용이라서 
어떤 방향으로 가는게 좋을 지에 대해서 한 번 이야기해보고 싶어요. 

@koreanddinghwan

**Comment by koreanddinghwan** [comment]
2번 안으로하면 service layer에서 2개의 repository 메서드를 호출하는게 나아보여요

**Comment by koreanddinghwan** [comment]
2번안대로하면 query에 프론트에서 찾을 status들 원하는거 콜해서 찾는 그림일 것 같네요

**Comment by JuneParkCode** [comment]
넵 
구조적으로는 어떻게 보세요?

**Comment by koreanddinghwan** [comment]
> 넵 구조적으로는 어떻게 보세요?

프론트쪽에 로직 넘기는게 부담스러웠어서 직접 만드는거였는데, 이렇게되면 큰 문제는 없을거라고 생각합니다

**Comment by JuneParkCode** [comment]
그러면 2안으로 일단 진행해보겠습니다. #84  이거 해결하고 진행할게요.

**Comment by koreanddinghwan** [comment]
넵 감사합니다
